### PR TITLE
add overlay fusion to fuse without blending

### PR DESCRIPTION
**Pull request by joshua-gould**

### CODE REVIEW

**Comment by m-albert** [comment]
@joshua-gould thanks for the PR! I'm not sure yet what's your idea with the fusion method proposed in the PR, could you detail a bit?

**Comment by joshua-gould** [comment]
This function can be used to disable blending by using the pixels only in the first tile in an overlapping region.

**Comment by m-albert** [comment]
Oh I see. Of course, that makes sense.

Here's something to consider though: When the output chunk contains both overlapping and non-overlapping regions, specifically those in which the first view is zero, the resulting fusion would contain zeros. Therefore I think probably a "first available view" fusion would make sense. Given this more general case, it'd also be good to get the linear blending work with this function.

Do you have a use case for the function as it is in the PR (i.e. without considering other views when the first view is not covering the full output chunk)?

**Comment by joshua-gould** [comment]
I did not consider that the output chunk could contain both overlapping and non-overlapping regions and don't have a need for pull request as is. Thanks.

**Comment by m-albert** [comment]
Okay! While I don't have the bandwidth right now to implement this, it's good to keep this feature in mind though.

I'm adding some commits here (also have a local copy) for future reference.

**Pull request closed without merging**
