### PR TITLE
Upgrade to https://bioio-devs.github.io/bioio/MIGRATION.html

### PR DESCRIPTION
**Pull request by joshua-gould**

### CODE REVIEW

**Comment by m-albert** [comment]
Oh, [napari-stitcher](https://github.com/multiview-stitcher/napari-stitcher) will also need to be adapted. Putting this here mainly to not forget!

**Comment by m-albert** [comment]
@joshua-gould Thanks again for getting in the upgrade from `aicsimageio` to `bioio` 🙏

Your changes look good to me.

While I completely agree that `io.read_mosaic_image_into_list_of_spatial_xarrays` is not an optimal function name , I'd prefer to keep it for now and modify it together with some more API changes.

Merging this!

**Review by m-albert — APPROVED** [review]

**Comment by joshua-gould** [comment]
Hi, is there a reason that this pull request was reverted? I'm happy to update the code to fix any issues.

**Comment by m-albert** [comment]
Hi @joshua-gould , thanks for checking in here. There had been some compatibility issue (I think also related to `napari-stitcher`) which unforunately I'm not able to reconstruct right now.

**Pull request merged**
